# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: adesso AG DevBlog
subline: Unsere Plattform für Wissenstransfer und Austausch 
email: 
description: "adesso sorgt als unabhängiger IT-Dienstleister durch Beratung und Softwareentwicklung für den Erfolg Ihrer Projekte und die Zukunftssicherheit Ihrer Anwendungen."
blog_intro: "In unserem Blog nehmen wir Sie mit auf eine spannende Reise quer durch das riesige Repertoire unserer Themenexperten. Von den großen Technologiethemen über die kleinen Nischen-Topics, über Future Trends und praktische Programmiertipps. Von Fach- und Karrierethemen bis hin zu allgemeinen Unternehmens-Stories. Und wir freuen uns darauf, uns mit Ihnen zu all diesen Themen auszutauschen. Denn Meinungsaustausch und Dialog sind für uns die besten Voraussetzungen, um uns weiterzuentwickeln und immer den entscheidenden Schritt voraus zu sein. Wir sind gespannt auf Ihre Meinung, Ihre Anregungen und auf fruchtbare Diskussionen."
# Outputtig
# permalink: possible that it is been owerwritten by the plugin 'multipost.rb' within the 
# _plugins directory
permalink: blog-posts/:year-:month-:day/:title.html
# paginate: 3 # amount of posts to show
# paginate_path: /pages/page:num/

# Serving
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username: "adessoAG"

# Build settings
markdown: kramdown
kramdown: 
  syntax_highlighter_opts:
    disable : true
  auto_ids: true
  header_offset: 3
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# declare Timezone to make building possible
timezone: Europe/Berlin

#Pagination
paginate: 10

mini_magick:
    fullScreen_1600:
        source: /assets/images/original/
        destination: /assets/images/FullScreenPicture/resolution1600
        crop: "1920x1070+0+0"
        gravity: "center"
    fullScreen_1440:
        source: /assets/images/original/
        destination: /assets/images/FullScreenPicture/resolution1440
        crop: "1400x1090+232+0"
        gravity: "center"
    fullScreen_1200:
        source: /assets/images/original/
        destination: /assets/images/FullScreenPicture/resolution1200
        crop: "1440x1020+212+30"
        gravity: "center"
    fullScreen_1024:
        source: /assets/images/original/
        destination: /assets/images/FullScreenPicture/resolution1024
        crop: "1536x1200+164-60"
        gravity: "center"
    fullScreen_768:
        source: /assets/images/original/
        destination: /assets/images/FullScreenPicture/resolution768
        crop: "1152x940+370+65"
        gravity: "center"
    fullScreen_600:
        source: /assets/images/original/
        destination: /assets/images/FullScreenPicture/resolution600
        resize: "600x470+786+330"
        gravity: "center"
    fullScreen_480:
        source: /assets/images/original/
        destination: /assets/images/FullScreenPicture/resolution480
        crop: "480x615+758+200"
        gravity: "center"
    fullScreen_0:
        source: /assets/images/original/
        destination: /assets/images/FullScreenPicture/resolution0
        crop: "640x864+758+133"
        gravity: "center"
    PicturesSideBySide_1600:
        source: /assets/images/original/
        destination: /assets/images/PicturesSideBySide/resolution1600
        crop: "640x864+758+133"
        gravity: "center"
    PicturesSideBySide_1440:
        source: /assets/images/original/
        destination: /assets/images/PicturesSideBySide/resolution1440
        crop: "640x864+758+133"
        gravity: "center"
    PicturesSideBySide_480:
        source: /assets/images/original/
        destination: /assets/images/PicturesSideBySide/resolution480
        crop: "640x864+758+133"
        gravity: "center"
    TextPictureParagraph_1600:
        source: /assets/images/original/
        destination: /assets/images/TextPictureParagraph/resolution1600
        crop: "640x864+758+133"
        gravity: "center"
    TextPictureParagraph_1440:
        source: /assets/images/original/
        destination: /assets/images/TextPictureParagraph/resolution1440
        crop: "640x864+758+133"
        gravity: "center"
    TextPictureParagraph_480:
        source: /assets/images/original/
        destination: /assets/images/TextPictureParagraph/resolution480
        crop: "640x864+758+133"
        gravity: "center"
    

# Plugins
plugins:
  - liquid-md5
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-minimagick
  
exclude:
  - assets/first-spirit-xml
  - examples/
